### ISSUE TITLE
robustnejsi chroustani .dat

### ISSUE THREAD

**Issue by ljocha** [CERIT-SC/saxs-ensamble-fit#2]
Bude toho asi vic, ale pro prvni priblizeni, jsou-li v souboru radky se samymi rovnitky, lze ocekvat format:

Komentare
...
=======
q I err
...
========
Komentare
....

Je to potreba s trochou heuristiky rozebrat a komentare vykosit.

Lepe v zakladnim pracovnim adresari zachovat soubor s komentari (aby se dal downloadovat zpatky as is) a vyrezani komentaru udelat bokem.

**Comment by krab1k** [comment]
Vzal jsem to podle toho příkladu, co neprošel, kde jsou ty vlastní data odděleny "=====". Tohle už je OK. V tuto chvíli by mělo být  spraveno v 998ba9002bce52c109ee266279663442d62013fd. Pro teď bych to zavřel, pokud se objeví ještě nějaký další "formát", lze znovu otevřít.
